AWSTemplateFormatVersion: '2010-09-09'
Description: Application Load Balancer, Target Group, and Listener

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC for ALB and Target Group

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for ALB

  ALBSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Existing ALB Security Group ID

  HttpPort:
    Type: Number
    Default: 80
    Description: ALB listener port

Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Scheme: internet-facing
      Subnets: !Ref SubnetIds
      SecurityGroups:
        - !Ref ALBSecurityGroupId

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 80
      Protocol: HTTP
      TargetType: instance
      HealthCheckProtocol: HTTP
      HealthCheckPort: traffic-port
      HealthCheckPath: /
      Matcher:
        HttpCode: '200-399'

  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: !Ref HttpPort
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

Outputs:
  LoadBalancerDNSName:
    Description: Public DNS name of the ALB
    Value: !GetAtt ApplicationLoadBalancer.DNSName

  TargetGroupArn:
    Description: ARN of the Target Group
    Value: !Ref TargetGroup
