version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  ApplicationStop:
    - location: deploy/scripts/stop.sh
      timeout: 120
      runas: root

  BeforeInstall:
    - location: deploy/scripts/login_ecr.sh
      timeout: 120
      runas: root

  AfterInstall:
    - location: deploy/scripts/pull.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: deploy/scripts/start.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: deploy/scripts/validate.sh
      timeout: 180
      runas: root