version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing Python dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 145023132787.dkr.ecr.us-east-1.amazonaws.com

  pre_build:
    commands:
      - echo "Preparing for Docker image build..."

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t fastapi-app .
      - docker tag fastapi-app:latest 145023132787.dkr.ecr.us-east-1.amazonaws.com/fastapi-app-ecr:latest

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push 145023132787.dkr.ecr.us-east-1.amazonaws.com/fastapi-app-ecr:latest
      - echo "Build and push complete."

artifacts:
  files: []
