version: 0.2
env:
  variables:
    IMAGE_REPO: fastapi-app-ecr
phases:
  pre_build:
    commands:
      - COMMIT_SHORT=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-10)
      - IMAGE_TAG=${COMMIT_SHORT:-latest}
      - IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO:$IMAGE_TAG"
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
  build:
    commands:
      - docker build -t "$IMAGE_URI" .
      - docker push "$IMAGE_URI"
      - jq --arg IMG "$IMAGE_URI" '(.containerDefinitions[] | select(.name=="fastapi-container") | .image) = $IMG' taskdef-template.json > taskdef.json
artifacts:
  files:
    - appspec.yaml
    - taskdef.json
  discard-paths: yes