version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pet_adoption_api_aws
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    command: >
      bash -c "
        alembic -c /app/alembic.ini upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 80
      "
    ports:
      - "80:80"
