AWSTemplateFormatVersion: '2010-09-09'
Description: Security Groups for EC2 and ALB

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Target VPC
  AdminCidr:
    Type: String
    Default: ''
    Description: Optional CIDR allowed to SSH to instances; blank disables SSH

Conditions:
  HasAdminCidr: !Not [ !Equals [ !Ref AdminCidr, '' ] ]

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access to instances
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP to ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceSecurityGroupId:
    Description: Instance SG ID
    Value: !Ref InstanceSecurityGroup

  ALBSecurityGroupId:
    Description: ALB SG ID
    Value: !Ref ALBSecurityGroup